# Generated by Django 2.2.6 on 2019-10-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RomanMaps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maps',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
