# Generated by Django 2.2.6 on 2019-10-20 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RomanMaps', '0002_auto_20191019_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maps',
            name='image',
            field=models.FileField(upload_to='images'),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='gallery')),
                ('maps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='RomanMaps.Maps')),
            ],
        ),
    ]
