# Generated by Django 2.2.6 on 2019-10-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RomanMaps', '0003_auto_20191020_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.FileField(upload_to='romanmaps/gallery'),
        ),
        migrations.AlterField(
            model_name='maps',
            name='image',
            field=models.FileField(upload_to='romanmaps/images/'),
        ),
    ]
