# Generated by Django 2.2.6 on 2019-10-20 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RomanMaps', '0004_auto_20191020_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maps',
            name='image',
        ),
    ]
