# Generated by Django 2.2.6 on 2019-10-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RomanMaps', '0005_remove_maps_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='romanmaps/gallery'),
        ),
    ]
